name: Daily Commit

on:
  schedule:
    # 每天 UTC 时间 00:00 触发（北京时间 08:00）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 手动触发

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create empty commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Daily commit"

      - name: Push changes
        run: git push origin main
