# 位置: .github/workflows/daily-commit.yml
name: Daily Commit

on:
  schedule:
    # 每天 UTC 时间 00:00 触发（北京时间 08:00）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 手动触发

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create or switch to action-commit branch
        run: |
          git checkout -B action-commit

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create empty commit
        run: git commit --allow-empty -m "Daily commit"

      - name: Push changes
        run: |
          for i in {1..3}; do
            git push origin action-commit && exit 0
            sleep 5
          done
          exit 1
